# Generated by Django 2.2.2 on 2019-06-15 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifier',
            name='model',
            field=models.CharField(default='random_forest', max_length=100),
            preserve_default=False,
        ),
    ]
