# Generated by Django 2.2.2 on 2019-06-14 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewsFeedback',
        ),
    ]
