# Generated by Django 2.2.2 on 2019-06-14 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20190614_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.RenameField(
            model_name='newspredictionfeedback',
            old_name='feedback',
            new_name='is_fake_news',
        ),
    ]
